publish_to: none
name: solana_wallet
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

executables:
  cyclone-anchor-idl:

dependencies:
  pointycastle: ^3.7.3
  cryptography:
    git:
      url: https://github.com/bransundae/cryptography
      ref: master
      path: cryptography
  hex: any
  fixnum: ^1.1.0
  http: ^0.13.5
  logging: ^1.2.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.0
  test: any
