enum SystemInstruction {
  createAccount,
  assign,
  transfer,
  createAccountWithSeed,
  advanceNonceAccount,
  withdrawNonceAccount,
  initializeNonceAccount,
  authorizeNonceAccount,
  allocate,
  allocateWithSeed,
  assignWithSeed,
  transferWithSeed,
  updateNonceAccount,
}